trigger:
  branches:
    include:
      - main

pool:
  name: self-hosted  # Use a self-hosted agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

- script: |
    pip install -r requirements.txt
    pytest tests/test_sb_twin.py
  displayName: 'Run Selenium Tests'